### PR TITLE
Issue 177

### PR DESCRIPTION
**Pull request by Geolim4**
Global changes:

- Added phpDoc Block comment on class/method/properties
- Replaced **var** keyword with **public**
- Defined non-existing visibility (public, protected, private)
- Moved constructor to be first method position
- Commented unused/emty if/else conditions
- Improved return consistency, e.g: phpfastcache_xcache::driver_isExisting()

- Removed aliases:
 - is_writeable() => is_writable()

- Removed tab indentations (it hurt eyes so bad)
 
- Removed silent operator (as per #175):
 - sqlite.php
  - file_exists()
  - mkdir()
  
- Ignored:
 - phpfastcache/_extensions/predis-1.0/*
 - phpfastcache/_extensions/SSDB.php

### CODE REVIEW

**Comment by Geolim4** [comment]
Warning, i resolved a conflict on some files, can you check if a don't forget anything during the merge ?
Thanks.

# Conflicts:
#	phpfastcache/3.0.0/abstract.php
#	phpfastcache/3.0.0/drivers/files.php
#	phpfastcache/3.0.0/drivers/sqlite.php
#	phpfastcache/3.0.0/phpfastcache.php

**Comment by Geolim4** [comment]
Related issue: #177

**Comment by Geolim4** [comment]
Already merged ? Oo
So fast !

**Comment by khoaofgod** [comment]
I trust you, hahahaha

**Comment by khoaofgod** [comment]
it merged, but it's not a release yet. ^_^

**Comment by Geolim4** [comment]
Ok :)

**Comment by khoaofgod** [comment]
I will test it after work today or tmr before I draft a new release on this commit.
Thanks again for help me on this, I was overload from last summer.

**Comment by Geolim4** [comment]
You're welcome, i love readable and well-commented code :))

**Pull request merged**
